# Support routines for shell scripts

DIRS+=lib/shell
PROGS+=obj/lib/shell/config obj/lib/shell/logger

obj/lib/shell/config: obj/lib/shell/config.o $(LIBSH)
obj/lib/shell/logger: obj/lib/shell/logger.o $(LIBSH)
