# Support routines for shell scripts

DIRS+=lib/shell
PROGS+=obj/lib/shell/config obj/lib/shell/logger

obj/lib/shell/config: obj/lib/shell/config.o obj/lib/libsh.a
obj/lib/shell/logger: obj/lib/shell/logger.o obj/lib/libsh.a
