#!/usr/bin/perl
# A simple script for making releases of LibUCW
# (c) 2012--2014 Martin Mares <mj@ucw.cz>

use strict;
use warnings;
require "maint/release.pm";

my $r = new UCW::Release("libucw");
$r->{"test_compile"} = "./configure && make -j4";
$r->{"archive_dir"} = $ENV{"HOME"} . "/archives/libucw";
push @{$r->{"uploads"}}, { "url" => "scp://ftp.ucw.cz/~ftp/pub/libucw/" };

$r->ParseOptions;
$r->GetVersionFromGit;
$r->InitDist("maint/tmp");
my $reldir = $r->GenPackage;
$r->GenFile("README");
$r->Test;
$r->MakeArchive;
$r->Upload;

if ($r->{"do_upload"}) {
	my $tdir = $r->{"TESTDIR"};
	if (defined $tdir) {
		print "Generating documentation\n";
		`cd $tdir && make install-libucw-docs INSTALL_DOC_DIR=../doc INSTALL_MAN_DIR=../man`;
		die if $?;
		print "Upload of documentation\n";
		$r->Confirm;
		system qw(rsync -avz --delete maint/tmp/doc/ucw/ jw:/var/www/libucw/doc/);
		die if $@;
	} else {
		print "WARNING: With --notest, no documentation is published!\n";
	}
}
