#!/usr/bin/perl
# A simple script for making releases of LibUCW
# (c) 2012 Martin Mares <mj@ucw.cz>

use strict;
use warnings;
require "maint/release.pm";

my $r = new UCW::Release("libucw");
$r->{"test_compile"} = "./configure && make -j4";
$r->{"archive_dir"} = $ENV{"HOME"} . "/archives/libucw";
push @{$r->{"uploads"}}, { "url" => "scp://ftp.ucw.cz/~ftp/pub/libucw/" };

$r->ParseOptions;
$r->GetVersionFromGit;
$r->InitDist("maint/tmp");
my $reldir = $r->GenPackage;
$r->GenFile("README");
$r->Test;
$r->MakeArchive;
$r->Upload;

# my $tdir = $r->{"TESTDIR"};
# if (defined $tdir) {
# } else {
# 	print "WARNING: With --notest, no documentation is published!\n";
# }
