#!/bin/sh
# Generate all data files for the charset conversion library
# (c) 2001--2003 Martin Mares <mj@ucw.cz>

set -ex
rm -f U-*.h chartable.h misc/u-*
misc/gen-basic
misc/table2h _U_cat byte <misc/u-cat >U-cat.h
misc/table2h _U_lower word <misc/u-lower >U-lower.h
misc/table2h _U_upper word <misc/u-upper >U-upper.h
misc/gen-unacc >misc/u-unacc
misc/table2h _U_unaccent word <misc/u-unacc >U-unacc.h
misc/gen-ligatures >U-ligatures.h
misc/gen-charconv <misc/chartable.in >chartable.h
