# Makefile for the UCW Sorter (c) 2007 Martin Mares <mj@ucw.cz>

DIRS+=lib/sorter

LIBUCW_MODS+=sorter/config sorter/govern sorter/sbuck

$(o)/lib/sorter/sort-test: $(o)/lib/sorter/sort-test.o $(LIBUCW)
