# Tests related to the new sorter

DIRS+=debug/sorter
PROGS+=$(addprefix $(o)/debug/sorter/,retros radix-file-test radix-asio-test)

$(o)/debug/sorter/retros: $(o)/debug/sorter/retros.o $(LIBSH)
$(o)/debug/sorter/radix-file-test: $(o)/debug/sorter/radix-file-test.o $(LIBSH)
$(o)/debug/sorter/radix-asio-test: $(o)/debug/sorter/radix-asio-test.o $(LIBSH)
